name: Pull request checks

on:
  pull_request:
    branches:
      - develop
      - master
      - main

jobs:
  check-style:
    name: Check Python style and run tests

    runs-on: ubuntu-latest
    # image: python:3.8-buster
    steps:
      - uses: actions/checkout@v2

      - name: Install development requirements
        run: make requirements-dev && requirements-lint

      - name: Flake
        run: make flake

      - name: Run tests
        run: make run-tests
